CREATE DATABASE LOGICAL_ASSESSMENT;

USE LOGICAL_ASSESSMENT;

CREATE TABLE QUESTION_PAPER (
  ID int not null auto_increment,
  NAME varchar(10) not null,
  PRIMARY KEY(ID)
);

CREATE TABLE QUESTION (
  ID int not null auto_increment,
  QUESTION_PAPER_ID int not null,
  POSITION int not null,
  ANSWERS varchar(50) not null,
  PRIMARY KEY(ID),
  CONSTRAINT U_QP_POS_ID UNIQUE (QUESTION_PAPER_ID, POSITION),
  CONSTRAINT QP_ID_FK FOREIGN KEY(QUESTION_PAPER_ID) REFERENCES QUESTION_PAPER
);



